# Generated by Django 4.2.2 on 2023-06-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image_url_profile_last_failed_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_failed_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_logged',
            field=models.DateTimeField(null=True),
        ),
    ]
