# Generated by Django 4.2.2 on 2023-06-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_last_failed_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_logged',
        ),
    ]
