# Generated by Django 4.2.2 on 2023-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_failed_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
